engines:
    coverage:
        enabled: true
        exclude_paths:[
            - 'test/**'
            - '/src/main/java/ar/edu/unq/virtuaula/*.{java,class}'
            - '/src/main/java/ar/edu/unq/virtuaula/util/JwtTokenUtil.java'
            - '/src/main/java/ar/edu/unq/virtuaula/security/JwtRequestFilter.java'
            - '/src/main/java/ar/edu/virtuaula/controller/**'
            - '/src/main/java/ar/edu/unq/virtuaula/dto/**'
        ]
    metrics:
        enabled: true
    duplication:
        enabled: true
