language: java

jdk:
  - openjdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE virtuaula;'
  - mysql -e 'USE virtuaula;'
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - chmod +x gradlew

before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

after_success:
  - bash <(curl -k -Ls https://coverage.codacy.com/get.sh)