INSERT INTO option_task (response_value, task_id) values ('x = -1', 1);
INSERT INTO option_task (response_value, task_id) values ('x = 1', 1);
INSERT INTO option_task (response_value, task_id) values ('x = 2', 1);
INSERT INTO option_task (response_value, task_id) values ('x = -2', 1);
INSERT INTO option_task (response_value, task_id) values ('x = -1', 2);
INSERT INTO option_task (response_value, task_id) values ('x = 1', 2);
INSERT INTO option_task (response_value, task_id) values ('x = 2', 2);
INSERT INTO option_task (response_value, task_id) values ('x = -2', 2);
INSERT INTO option_task (response_value, task_id) values ('x = -1', 3);
INSERT INTO option_task (response_value, task_id) values ('x = 1', 3);
INSERT INTO option_task (response_value, task_id) values ('x = 2', 3);
INSERT INTO option_task (response_value, task_id) values ('x = -2', 3);
INSERT INTO option_task (response_value, task_id) values ('1939', 4);
INSERT INTO option_task (response_value, task_id) values ('1945', 4);
INSERT INTO option_task (response_value, task_id) values ('1986', 4);
INSERT INTO option_task (response_value, task_id) values ('1914', 4);
INSERT INTO option_task (response_value, task_id) values ('1939', 5);
INSERT INTO option_task (response_value, task_id) values ('1945', 5);
INSERT INTO option_task (response_value, task_id) values ('1986', 5);
INSERT INTO option_task (response_value, task_id) values ('1914', 5);
INSERT INTO option_task (response_value, task_id) values ('1939', 6);
INSERT INTO option_task (response_value, task_id) values ('1945', 6);
INSERT INTO option_task (response_value, task_id) values ('1986', 6);
INSERT INTO option_task (response_value, task_id) values ('1914', 6);